// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRTRxaQeUNXlwQGuD6CMG-yJX69FKqJFI',
    appId: '1:865193514231:web:153827fdcf2246673c6ff2',
    messagingSenderId: '865193514231',
    projectId: 'todolist-app-d7703',
    authDomain: 'todolist-app-d7703.firebaseapp.com',
    storageBucket: 'todolist-app-d7703.appspot.com',
    measurementId: 'G-8XHRSHCZVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzK7vbNe32DIBXuIBM5gr0Ao8acGsa-ew',
    appId: '1:865193514231:android:cde698915832ffd43c6ff2',
    messagingSenderId: '865193514231',
    projectId: 'todolist-app-d7703',
    storageBucket: 'todolist-app-d7703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOSvRr-rdoPDJxtF4-fFWVJTigoAcvseM',
    appId: '1:865193514231:ios:7277ae29a6a286303c6ff2',
    messagingSenderId: '865193514231',
    projectId: 'todolist-app-d7703',
    storageBucket: 'todolist-app-d7703.appspot.com',
    iosClientId: '865193514231-3rphp4oea1ihnuv8sq1jsgqi8oqa16h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOSvRr-rdoPDJxtF4-fFWVJTigoAcvseM',
    appId: '1:865193514231:ios:7c1663d5aef5a4d03c6ff2',
    messagingSenderId: '865193514231',
    projectId: 'todolist-app-d7703',
    storageBucket: 'todolist-app-d7703.appspot.com',
    iosClientId: '865193514231-qbsqsoiosodt8quitia466d5n9urjstk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
